version: '3.1'

services:
  nginx:
    build:
      dockerfile: ./Dockerfile
      context: ./
    ports:
      - "8081:80"
    depends_on:
      - php

  mariaDB:
    image: mariadb:latest
    ports:
      - "3306:3306"
    depends_on:
      - nginx
    environment:
      - MYSQL_ROOT_PASSWORD=654321
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  php:
    image: php:7-fpm-alpine
    volumes:
      - ./src/details:/var/www/details
    ports:
      - "9000:9000"